### ISSUE TITLE
Customer Password not sent in admin

### ISSUE THREAD

**Issue by ClicShopping** [osCommerce/osCommerce-V4#1]
Hello,

When I create in admin a new customer, (no email is sent information to the customers, first problem)
But, When I update the password, the customer does not receive information about this new password.

smtp is set correctly in adminb side

**Comment by vladmalyshev** [comment]
did e-mail worked before you switched to SMTP sending way? did you recieved e-mail when settings was sendmail?

**Comment by ClicShopping** [comment]
Yes I received one, just one.

**Comment by vladmalyshev** [comment]
So just to check chonology. You try with standard setting, recieved e-mails ok and after that start changes settings and stop recieve. Right?

**Comment by ClicShopping** [comment]
My settings

E-Mail Transport Method | smtp
E-Mail Linefeeds | LF
Use MIME HTML When Sending Emails | TRUE
Verify E-Mail Addresses Through DNS | FALSE
Send E-Mails | TRUE
Send BCC copy of all email to | myemail@gmail.com
SMTP Mailer | None
SMTP Mailer Mandrill ApiKey |  
SMTP Host | smtp.test.org
SMTP Port | 465
SMTP Username | myemail
SMTP Password | mypassword*
SMTP Encryption | tls
Use Reminder? | FALSE
Send .webp images in emails | FALSE

**Comment by vladmalyshev** [comment]
to speed up the process please use my e-mail: vlad@holbi.co.uk, so we can discuss those points more quick. thanks.
