### ISSUE TITLE
Template button (widget, save ....) does not work very well

### ISSUE THREAD

**Issue by ClicShopping** [osCommerce/osCommerce-V4#11]
When I want to customize the template, soem action does not work
For moment the widget button, save ... does not work very well. For example, you want to display a new widget, you do not see this widget on your screen (but the action is created)
You must save, close the current design and after come back to this design to see your action.

When you start a design, some action can be correct but after that when you want to create an action to customize your design nothing happen, but the system save your action.

in this case, you can click, 3, 4 times on the button, you dot see anything, just when you come back to see your design, you see all this actions you have created before.

**Comment by pan-oscom** [comment]
Could not reproduce. Seems it fixed
