### ISSUE TITLE
Customer group and sales channel

### ISSUE THREAD

**Issue by ClicShopping** [osCommerce/osCommerce-V4#12]
Hello,

When you activate in customer goup this option for example : New customers need approve? 
this option is applied for all channel.
It's not possible to customize a specific channel one with this option, another with another option.
Or supermarket channel and watch need maybe different approach (example).

**Comment by ynechitajlo** [comment]
You can customize group for each sales channel.
find in Configuration :: Customer Details next options:
Default user group
Default visitor group
And click on install button. After that go to Sales channels and click on button Configuration in action panel.  Do this for each channel where the group should be different from the default.
