### ISSUE TITLE
OSC4 not working on Xampp 8

### ISSUE THREAD

**Issue by saisoftindia** [osCommerce/osCommerce-V4#15]
OSC4 not working on Xampp 8 after installed osc4, showing in use site 

Oops!
We can't seem to find the page you're looking for

and in admin site Access denied.
![image](https://user-images.githubusercontent.com/111063482/184139046-dc73d88a-c204-4b94-9918-019df5767a59.png)
![image](https://user-images.githubusercontent.com/111063482/184139085-88c3ec0c-b3c1-4080-a107-21a90d834efe.png)

**Comment by pan-oscom** [comment]
fixed
