### ISSUE TITLE
Password not sent catalog side

### ISSUE THREAD

**Issue by ClicShopping** [osCommerce/osCommerce-V4#2]
Hello,

When I want recover my password catalog side : https://test.com/furniture/account/password-forgotten
no email is sent by osC

smtp is set correctly in admin side

**Comment by pan-oscom** [comment]
Use [Email History Report](https://www.oscommerce.com/app/emails-history-report) application to check the status of all sent emails.
Please use [our forum](https://www.oscommerce.com/forums/) for non-programming questions.
