### ISSUE TITLE
Doesn't run when database name contains hyphen

### ISSUE THREAD

**Issue by BrockleyJohn** [osCommerce/osCommerce-V4#20]
The range of characters that are valid the name of a database is broader than the range that don't need quoting in a query - this prevents the frontend loading although admin is fine.

e.g. database name myappdb-1234567890 gives 'please contact us if you see this page'

this is because the query to check the customer groups fails as the sql is 
select * from myappdb-1234567890.groups where groups_id = '1'
#1064 - You have an error in your SQL syntax

My solution was to edit line 108 of includes\database_tables.php, putting backticks round the database name.

**Comment by pan-oscom** [comment]
fixed in 55722 update
