### ISSUE TITLE
Bad wording when reinstalling

### ISSUE THREAD

**Issue by BernhardEriksson** [osCommerce/osCommerce-V4#22]
I had an other issue with oscommerce V4 so I wanted to try with a fresh installation, going to /install/ told me to remove the configure.php file. Since it never stated which one I renamed /includes/configure.php /includes/local/configure.php /admin/includes/configure.php and /admin/includes/local/configure.php

Reinstalling recreated the files:
/includes/local/configure.php
/admin/includes/local/configure.php

But not the other two resulting in a HTTP error 500, and the PHP log states that it can't find the two files. I would suggest changing the wording in install.class.php on line 86 to indicate which files should be removed.

**Comment by pan-oscom** [comment]
Thanks for the detailed report. We will change it in the next update.
