### ISSUE TITLE
Theme, Save button for widget settings does not always work

### ISSUE THREAD

**Issue by BernhardEriksson** [osCommerce/osCommerce-V4#25]
In Firefox the console reports:
NS_ERROR_FAILURE:
and
Empty string passed to getElementById()

And the dialog with the save button is still there. Works in Chrome without any output to the console.

Firefox console specifies line 551
              newWin.location.reload(localStorage.getItem('page-url')+'&is_admin=1');
in jquery.edit-blocks.js

If I understand the code correctly (which may not be the case since I've recently started looking at the code for v4) page-url is set in /watch/lib/backend/themes/basic/design/elements-tpl, but it may be empty since not all code gives url (that is then used to set page-url) a value that isn't an empty string.

**Comment by pan-oscom** [comment]
Could not reproduce, Maybe fixed.
