### ISSUE TITLE
NOT IS NULL not supported in MariaDB

### ISSUE THREAD

**Issue by BernhardEriksson** [osCommerce/osCommerce-V4#26]
In
/lib/common/helpers/Categories.php NOT IS NULL is used twice. This is not supported in MariaDB ( https://mariadb.com/kb/en/is-not-null/ ) and should be changed to IS NOT NULL

**Comment by BernhardEriksson** [comment]
Same problem is also in
/lib/backend/models/EP/Provider/Brands.php line 95

**Comment by pan-oscom** [comment]
Thanks. Will be fixed in the next update.
