### ISSUE TITLE
Pre-installation check does not check version of the database

### ISSUE THREAD

**Issue by BernhardEriksson** [osCommerce/osCommerce-V4#27]
There are several comments in the forum from people have not been able to install v4 but not knowing why. Since other checks are made I suggest adding a check for mysql/mariadb version to the pre-installation check to reduce the number of reports of this.

https://www.php.net/manual/en/mysqli.get-server-info.php
https://www.php.net/manual/en/pdo.getattribute.php

**Comment by pan-oscom** [comment]
Thanks. Will be added in the next version.
