### ISSUE TITLE
Recaptcha not working

### ISSUE THREAD

**Issue by Jack-osc** [osCommerce/osCommerce-V4#33]
I have a customer account on the site. It was working but now it doesn't. When I try the password forgotten the page shows a recaptcha failure. This is a test site so getting new keys from google would be wasted effort. And since it was working, I assume the included keys are global. I have verified the account exists in admin and even tried changing the password there to make sure it is correct. Is there a way to turn recaptcha off? If not, what is the fix for this? The attached shows the error.

![fail_recaptcha](https://user-images.githubusercontent.com/123400839/214106060-9c4f557d-5cc0-4b44-b5a5-088da52d4888.jpg)

**Comment by pan-oscom** [comment]
The Google Recaptcha is disabled by default into 56860 update
