### ISSUE TITLE
Error (#2) An internal server error occurred.

### ISSUE THREAD

**Issue by jlpitalua** [osCommerce/osCommerce-V4#34]
Hola buenas tardes

Estoy instalando oscommerce 4 y ya se instalo, pero al momento de entar a la sección del adminstrador me envia mensaje de error:

Hello, good afternoon

I am installing oscommerce 4 and it is already installed, but when I enter the administrator section it sends me an error message:

Error (#2)
An internal server error occurred.
The above error occurred while the Web server was processing your request.

Please contact us if you think this is a server error. Thank you.

Que puedo hacer para solucionarlo?'
Agradezco mucho su compresión y apoyo

What can I do to fix it?'
I really appreciate your understanding and support.

**Comment by faisalhardianysyah** [comment]
i have some problem

**Comment by faisalhardianysyah** [comment]
> 

I have found a way to solve this problem, please upload php maileir to your hosting, the php file is attached
[PHPMailer-master.zip](https://github.com/osCommerce/osCommerce-V4/files/10905308/PHPMailer-master.zip)

**Comment by 1KShea** [comment]
> > 
> 
> I have found a way to solve this problem, please upload php maileir to your hosting, the php file is attached [PHPMailer-master.zip](https://github.com/osCommerce/osCommerce-V4/files/10905308/PHPMailer-master.zip)

What OScV4 dir is this to be placed in?

**Comment by pan-oscom** [comment]
It seems your default email handler into php.ini is not configured correctly.
Since 56860 update that problem does not crash the page.
