### ISSUE TITLE
please contact us if you see this page

### ISSUE THREAD

**Issue by prokoleg** [osCommerce/osCommerce-V4#35]
When I entered the store, I saw this message. backend is working normally. What could be the reason for this? This error occurs regularly when the page is refreshed. Error.log attached
`[Thu Mar 30 17:59:02.598178 2023] [php:error] [pid 31210] [client 127.0.0.1] PHP Fatal error:  Type of SmartyCompilerException::$line must be int (as in class Exception) in /var/www/site.local/www/lib/vendor/smarty/smarty/libs/sysplugins/smartycompilerexception.php on line 8

[Thu Mar 30 17:59:02.876524 2023] [php:error] [pid 31186] [client 127.0.0.1:56818] PHP Fatal error:  Type of SmartyCompilerException::$line must be int (as in class Exception) in /var/www/site.local/www/lib/vendor/smarty/smarty/libs/sysplugins/smartycompilerexception.php on line 8, referer: https://site.local/

[Thu Mar 30 18:03:57.867364 2023] [php:error] [pid 31217] [client 127.0.0.1:63446] PHP Fatal error:  Type of SmartyCompilerException::$line must be int (as in class Exception) in /var/www/site.local/www/lib/vendor/smarty/smarty/libs/sysplugins/smartycompilerexception.php on line 8

[Thu Mar 30 18:05:50.467378 2023] [php:error] [pid 31192] [client 127.0.0.1:32971] PHP Fatal error:  Type of SmartyCompilerException::$line must be int (as in class Exception) in /var/www/site.local/www/lib/vendor/smarty/smarty/libs/sysplugins/smartycompilerexception.php on line 8

[Thu Mar 30 18:08:13.917751 2023] [php:error] [pid 31218] [client 127.0.0.1:23812] PHP Fatal error:  Type of SmartyCompilerException::$line must be int (as in class Exception) in /var/www/site.local/www/lib/vendor/smarty/smarty/libs/sysplugins/smartycompilerexception.php on line 8
`

**Comment by codehog** [comment]
Which version of PHP are you running?  

Just wondering if this issue is related to "Smarty is not compatible with PHP 8.1"  ( https://github.com/smarty-php/smarty/issues/671 )

**Comment by prokoleg** [comment]
Thank you! I did not know that Smarty is not compatible with PHP8.1 and above.
