### ISSUE TITLE
##CUSTOMER_FIRSTNAME##, ##CUSTOMER_LASTNAME## not populated on "SEND VOUCHER" email template

### ISSUE THREAD

**Issue by codehog** [osCommerce/osCommerce-V4#39]
In the "send voucher" email template under "user related template from admin", 
when this is sent, the field for  ##CUSTOMER_FIRSTNAME## is replaced with nothing resulting in an email starting:

**Dear ,**

To replicate: goto **ADMIN -> Orders / Customers -> Customers**
- Click on a customer record you have email access to
- Click the Send coupon button on the right hand side
- Enter a few details and click **SEND**

To resolve, In Gv_mailController.php :: the fields for $mail['customers_firstname'] and $mail['customers_lastname'] are not being storedd in the $email_params array when there is a successful query before calling \common\helpers\Mail::get_parsed_email_template(

**Comment by pan-oscom** [comment]
Thanks. Your patch included into 56860 update
