### ISSUE TITLE
Updates kill website. 

### ISSUE THREAD

**Issue by Nefandous1** [osCommerce/osCommerce-V4#44]
Today I saw that I needed to do 2 version updates to put the system up to date and the current version.  This made me apprehensive because I had previous issues doing updates. 

In January I installed the 4.8 full download.  I started to modify the website and created my own theme with the theme creator which I eventually got used to - although I'm used to coding the bare PHP code and putting 90% of it into the SQL database makes things pretty difficult.  I started to put products into the database, and in February OScommerce had updated to OSC version 4.10 and was having some issues with the update (PHP, SQL and other servers settings needed to be upgraded to use the versions) but I sorted these things out myself when I looked at the minimum specs needed. 

I got messages that there were updates and went into the update section and updated the shop to 4.11 and a major disaster; basically the updates killed the site!  I couldn't get into the frontend OR the backend and got server error codes.  I thought about posting this very same issue then, but thought it may be me (I'm not used to the new system), or maybe the server wasn't compatible or configured properly.   I had only put 200 or so items into the database and decided to start from scratch.  I deleted everything and reinstalled OSC4.11 directly onto the server without need to do updates and everything seemed fine.  It was a day and a half later....Yes, it took that long to delete everything, reinstall the shell and database, configure the backend, the frontend and start putting the data back in.  I reinstall the product data, and got everything working OK again....Although I have to go through each item to allocate pictures, suppliers and activate each one.  I don't know about anyone else, but it takes 2 hours just to make a copy of my current website of over 70k files!

So everything was working well till April or May and there was another version update.  I'd put over 1.5k items into the database around this time and my initial thought was....maybe I won't update with what happened last time.  But I talked myself into updating.  This was a big mistake!  The update broke the site again!!  I had made backups as previously, but with the months gone by I had tweeked everything the way I needed it to be, and I still needed to configure the bare site rather than save the old one over it.  And the way OSC v4 is, I have to put images into each item and can't do a mass upload!  So lots of work, this time a couple of weeks to get back to the where I'd been before installing the updates.

Which brings me to this afternoon.  It seems the updates are fine on an unmodified site (I've done the updates after a fresh install and know this is the case) however, if the site has been modified the updates kill the site completely.  Right now (as previously) I can not access either front nor backend.  I have a (#42S02) server Error and have got 3.5k items in my database that I will have to start from scratch again to salvage.

**Comment by pan-oscom** [comment]
The update 4.12 is a heavy because it contains a lot of files. 
Sometimes the webserver can kill the update script and the update does not complete correctly.
But you can restore your site completely, please read this post:
[https://www.oscommerce.com/forums/topic/499062-new-update-crashed/?do=findComment&comment=1832065](https://www.oscommerce.com/forums/topic/499062-new-update-crashed/?do=findComment&comment=1832065)

**Comment by Nefandous1** [comment]
Yeah I've changed the php memory max to 512mb as per the update thread you posted.

And I've now got the site back by copying all the new files over into the directories.  But still can't "apply migrations".  My hosting provider has turned off SSH, so I can't use the terminal or shell.  And I've tried using the applymigrations_56860.php file only to get lots more errors.
........................

Start

Warning: session_set_save_handler(): Session save handler cannot be changed after headers have already been sent in /******/******/public_html/******/includes/functions/sessions.php on line 90

Warning: session_name(): Session name cannot be changed after headers have already been sent in /******/******/public_html/******/includes/functions/sessions.php on line 160

Warning: session_save_path(): Session save path cannot be changed after headers have already been sent in /******/******/public_html/******/includes/functions/sessions.php on line 176

Warning: session_set_cookie_params(): Session cookie parameters cannot be changed after headers have already been sent in /******/******/public_html/******/includes/application_top_console.php on line 165
Error: session_start(): Session cannot be started after headers have already been sent
#0 /******/******/public_html/******/lib/common/classes/TlErrorHandler.php(63): yii\base\ErrorHandler->handleError(2, 'session_start()...', '/******/******/...', 129) #1 [internal function]: common\classes\TlErrorHandler->handleError(2, 'session_start()...', '/******/******/...', 129) #2 /******/******/public_html/******/includes/functions/sessions.php(129): session_start() #3 /******/******/public_html/******/lib/common/components/SessionFlow.php(111): tep_session_start() #4 /******/******/public_html/******/lib/vendor/yiisoft/yii2/base/Application.php(325): common\components\SessionFlow->bootstrap(Object(yii\console\Application)) #5 /******/******/public_html/******/lib/vendor/yiisoft/yii2/base/Application.php(271): yii\base\Application->bootstrap() #6 /******/******/public_html/******/lib/vendor/yiisoft/yii2/console/Application.php(124): yii\base\Application->init() #7 /******/******/public_html/******/lib/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\console\Application->init() #8 /******/******/public_html/******/lib/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array) #9 /******/******/public_html/******/lib/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array) #10 /******/******/public_html/******/apply.php(27): yii\console\Application->__construct(Array) #11 {main}

--------------

I tried re-doing the update with the Update section in the Admin, then forcing the update, but I got a lot of mysql errors and ended up having to put the site back over itself.

Any ideas to what the issue is? and should I just revert to the previous version and then redo the update from scratch?
