### ISSUE TITLE
Install README.md is missing directories than need write

### ISSUE THREAD

**Issue by xtronics** [osCommerce/osCommerce-V4#47]
Got errors - 
file_put_contents(./../includes/local/configure.php): Failed to open stream: No such file or directory

Hung install - seems that /admin/includes/local needs write.. 
A simple bash script to set the permissions would be nice.. 

Others are probably not running into this by setting all directories writable?

**Comment by xtronics** [comment]
Also lib/common/config/params-local.php): Failed to open stream: Permission denied 
So /lib/common/config/ needs write..

**Comment by pan-oscom** [comment]
> Others are probably not running into this by setting all directories writable?

Since osCommerce supports system updates, all directories must be writable
