### ISSUE TITLE
Not being able to save in any menu 

### ISSUE THREAD

**Issue by iplayradionetworks** [osCommerce/osCommerce-V4#48]
Hi . 

After installing the app either solely as a downloaded package, uploaded via ftp and setup ... or either installed via softaculous platform, the user (admin) has no ability to save . 

No matter following any guides or changing the key code as suggested after installation, into the local.php file . It won't allow you to clear OPcache or any cache at all . 

You just sit and wait and nothing happens .

All requirements are being met but nothing .

Any ideas ?

**Comment by pan-oscom** [comment]
Please create a thread on [our forum](https://www.oscommerce.com/forums/) and attach some screenshot to illustrate the issue.

**Comment by iplayradionetworks** [comment]
I am trying to but I get an error regarding captcha. 

"This site key is not enabled for the invisible captcha"

Anyhow... See some screenshots

![Screenshot_20230630_090050_Chrome.jpg](https://github.com/osCommerce/osCommerce-V4/assets/40426604/c9dd89f3-65cf-4476-a9b0-06a4a4d6f704)

![Screenshot_20230630_090032_Chrome.jpg](https://github.com/osCommerce/osCommerce-V4/assets/40426604/5a8fe38e-c949-465f-bc44-8a6e78bcee17)

![Screenshot_20230630_090119_Chrome.jpg](https://github.com/osCommerce/osCommerce-V4/assets/40426604/415c37a8-67bf-40be-bbd3-017615fd1137)

**Comment by pan-oscom** [comment]
You did not include an url in your screenshots. The url begins with http:// or https://?
