### ISSUE TITLE
Self-service set up metadata is showing up at the front end

### ISSUE THREAD

**Issue by jessicana** [osCommerce/osCommerce-V4#49]
When I fill the Self-service set up metadata in the SEO tab of any product as per the below, it is shown at the from end:

![image](https://github.com/osCommerce/osCommerce-V4/assets/7415824/14a047ee-1f1c-4d14-88a9-af004db997c4)

Front end:

![image](https://github.com/osCommerce/osCommerce-V4/assets/7415824/82f6d3f2-8819-42f3-b0c1-828917ad8f9c)

Is this how this is intended to be?

**Comment by pan-oscom** [comment]
Sure, you can add any tag for product <head> section:
![image](https://github.com/osCommerce/osCommerce-V4/assets/110422184/912745af-0a8f-414b-9530-2f4c29740394)
result:
![image](https://github.com/osCommerce/osCommerce-V4/assets/110422184/ef91e6e0-d1e5-4d8b-9e59-f97a4f1fe0d7)

Please use [our forum](https://www.oscommerce.com/forums/) for user-related questions for quick response.
