### ISSUE TITLE
Can't install osCommerce v4 on window 11

### ISSUE THREAD

**Issue by hel-samet** [osCommerce/osCommerce-V4#52]
Apache/2.4.56 (Win64)
OpenSSL/1.1.1t PHP/8.2.4
PHP version: 8.2.4

After i finished installation steps i get into this error

An Error occurred while handling another error:
ReflectionException: Class "currencies" does not exist in D:\users\File Project\osc_4_12_56860 (1)\lib\vendor\yiisoft\yii2\di\Container.php:507

Do anyone face kind of this problem? and any tips to resolve this problem?

**Comment by pan-oscom** [comment]
The current version of osCommerce does not support PHP 8.2
We will implement support for PHP 8.2 in the next version of osCommerce
