### ISSUE TITLE
Template customize button save

### ISSUE THREAD

**Issue by ClicShopping** [osCommerce/osCommerce-V4#6]
In customisation section, when you add a widget or change and after you want to save your action, nothing happen. 
Another moment for the same action, we have a quick reaction.
it's weird because we do not have any message.

Looking the log, there the error I see

`[01-Aug-2022 21:41:21 Europe/London] PHP Deprecated:  explode(): Passing null to parameter #2 ($string) of type string is deprecated in /home/mfvs8363/test.org/lib/common/helpers/Acl.php on line 624`

**Comment by pan-oscom** [comment]
Fixed
