### ISSUE TITLE
Database Backup Error

### ISSUE THREAD

**Issue by Lardonna8661** [osCommerce/osCommerce-V4#65]
When I try to backup database using your built database tool I get the following error:

Error
An internal server error occurred.
The above error occurred while the Web server was processing your request.

Please contact us if you think this is a server error. Thank you.

When i try to backup using phpmyadmin I get the following error:

TypeError: PhpMyAdmin\Export::getFilenameAndMimetype(): Argument #5 ($filenameTemplate) must be of type string, null given, called in /var/www/html/phpMyAdmin-5.2.1-all-languages/libraries/classes/Controllers/Export/ExportController.php on line 398

**Comment by pan-oscom** [comment]
> When I try to backup database using your built database tool I get the following error:
> 
> Error An internal server error occurred. The above error occurred while the Web server was processing your request.
> 
> Please contact us if you think this is a server error. Thank you.
> 
> When i try to backup using phpmyadmin I get the following error:
> 
> TypeError: PhpMyAdmin\Export::getFilenameAndMimetype(): Argument #5 ($filenameTemplate) must be of type string, null given, called in /var/www/html/phpMyAdmin-5.2.1-all-languages/libraries/classes/Controllers/Export/ExportController.php on line 398

Please use our forum for user related issues and questions: https://www.oscommerce.com/forums/

Most likely, your hosting has blocked the exec command, which is used to create an archive copy of the database.
