### ISSUE TITLE
Attribute image filename error

### ISSUE THREAD

**Issue by Goosub** [osCommerce/osCommerce-V4#67]
I found a bug in version: osc_4_14_63493

products_options_values_image column in debase is set to varchar(32) witch easily results in corrupt image filenames and images not showing.

There is also something buggy with the javascript that displays attribute image on entering edite mode in admin. 
It outputs a scr value with  "http:///" and I cant find the resposible javascript. Please help?

<div class="uploaded-image"><img src="http:///images/attributes/1-i-sw.webp">

**Comment by pan-oscom** [comment]
products_options_values_image column is practically not used and is left only for compatibility.
There are two extensions: Attributes Images and Inventory Images that uses other columns
