### ISSUE TITLE
ob_flush(): Failed to flush buffer. No buffer to flush while manually importing

### ISSUE THREAD

**Issue by c-store-cp** [osCommerce/osCommerce-V4#69]
In manual import, after assigning import fiels to csv rows, the above error is thrown.

Editiing /lib/backend/models/EP/Messages.php to exchange the three occurences of ob_flush with

if (ob_get_level() > 0) {ob_flush();}

fixed things for me.

Kind regards,

Chris

**Comment by pan-oscom** [comment]
Thanks. It will be fixed in the next update.
